[package]
name = "minix-rs"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "minix-rs"
path = "src/main.rs"

[dependencies]
minix-ipc = { workspace = true }
minix-sys = { workspace = true }
minix-mock = { workspace = true }

[lib]
name = "minix_rs"
path = "src/lib.rs"
