[package]
name = "minix-net-lwip"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "minix-net-lwip"
path = "src/main.rs"

[dependencies]
managed = { workspace = true }
smoltcp = { workspace = true }
minix-types = { workspace = true }
minix-sys = { workspace = true }
minix-sef = { workspace = true }
minix-netdriver = { workspace = true }
minix-sockdriver = { workspace = true }
minix-chardriver = { workspace = true }
minix-blockdriver = { workspace = true }

[lib]
name = "minix_net_lwip"
path = "src/lib.rs"
