[package]
name = "minix-vfs"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "minix-vfs"
path = "src/main.rs"

[dependencies]
minix-ipc = { workspace = true }
minix-sys = { workspace = true }
minix-mock = { workspace = true }
minix-types = { workspace = true }
bitflags = { workspace = true }

[dev-dependencies]
