[package]
name = "minix-init"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "minix-init"
path = "src/main.rs"

[dependencies]
minix-sys = { workspace = true }
minix-rt = { workspace = true, features = ["std"] }
minix-types = { workspace = true }
