[package]
name = "minix-driver-virtio_net"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "minix-driver-virtio_net"
path = "src/main.rs"

[dependencies]
minix-types = { workspace = true }
minix-sys = { workspace = true }

[lib]
name = "minix_driver_virtio_net"
path = "src/lib.rs"
