[package]
name = "minix-vm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "minix-vm"
path = "src/main.rs"

[dependencies]
minix-types = { workspace = true }
minix-sys = { workspace = true }
minix-arch = { path = "../../arch" }
bitflags = { workspace = true }

[lib]
name = "minix_vm"
path = "src/lib.rs"

[features]
default = ["bitmap_alloc"]
bitmap_alloc = []
segment_tree_alloc = []
buddy_alloc = []
vmstats = []
vm_acl_audit = []
