//! Build script for MFS: locates the packaged imgrd (if available) and
//! emits a generated source file with `include_bytes!`.
//!
//! During `xtask image`, the imgrd is generated by `mkfs_mfs` before this
//! crate is compiled (the xtask plan puts mfs build after imgrd generation).
//! For plain `cargo build` (host dev / tests), no imgrd exists and the
//! fallback is an empty slice — preserving the existing fail-closed
//! `PendingBlockSource` behaviour.
//!
//! C correspondence: the memory driver links imgrd via `_binary_imgrd_mfs_*`
//! (`drivers/storage/memory/local.h:5-9`). The Rust equivalent is this
//! `include_bytes!` at compile time, injected into the MFS binary directly
//! (E-FSBDEV minimal half: source.rs hands bytes to the file server process).

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let crate_dir = Path::new(&manifest_dir);
    // os/fs/mfs → os/target (two levels up to os/, then into target/)
    let target_dir = crate_dir.join("../../target");

    // Determine the target architecture from the build environment so we
    // never cross-contaminate (e.g. aarch64 build embedding x86_64 imgrd).
    // Host builds (cargo test) get arch_slug="" → no match → empty fallback.
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let arch_slug: &str =
        if target_os == "none" && (target_arch == "x86_64" || target_arch == "aarch64") {
            &target_arch
        } else {
            "" // host/test or unsupported arch: fall back to &[]
        };

    let imgrd_path = if arch_slug.is_empty() {
        None
    } else {
        let p = target_dir.join(format!("image/{}/imgrd.img", arch_slug));
        // Register rerun-if-changed unconditionally so that the file
        // appearing after a prior empty-build triggers recompilation.
        println!("cargo:rerun-if-changed={}", p.display());
        if p.exists() {
            Some(p)
        } else {
            None
        }
    };

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let gen_path = Path::new(&out_dir).join("imgrd_data.rs");

    if let Some(imgrd) = imgrd_path {
        let abs = imgrd
            .canonicalize()
            .expect("imgrd path canonicalization failed");
        let content = format!(
            "/// Auto-generated: packaged imgrd embedded via include_bytes!.\n\
             #[allow(dead_code)]\n\
             pub static BOOT_IMGRD_DATA: &[u8] = include_bytes!(r\"{}\")\n    ;\n",
            abs.display(),
        );
        fs::write(&gen_path, content).expect("write imgrd_data.rs");
    } else {
        // Dev/test fallback: empty (BOOT_IMGRD stays &[], PendingBlockSource).
        let content = "/// Auto-generated: no packaged imgrd found (dev/test mode).\n\
                       #[allow(dead_code)]\n\
                       pub static BOOT_IMGRD_DATA: &[u8] = &[];\n";
        fs::write(&gen_path, content).expect("write imgrd_data.rs");
    }
}
