//! ARM64 (aarch64) SMP implementation using the GICv3 interrupt controller.
//!
//! Implements `SmpArch` for ARM64 by programming the GIC (Generic Interrupt
//! Controller) v3 distributor to send Software Generated Interrupts (SGIs),
//! acknowledging IPIs via the CPU-interface system registers, and booting
//! Application Processors through PSCI (Power State Coordination Interface).
//!
//! # SMP mechanism overview
//!
//! - **IPI send**: An SGI (Software Generated Interrupt) is generated by
//!   writing the GICD_SGIR register in the distributor. The target CPU is
//!   selected by a CPU target list. We use SGI 0 as the schedule IPI.
//! - **IPI acknowledge**: The CPU interface exposes the active interrupt
//!   through ICC_IAR1_EL1 (Interrupt Acknowledge Register). Reading it
//!   drops the priority and returns the INTID; writing the same INTID to
//!   ICC_EOIR1_EL1 (End Of Interrupt Register) completes handling.
//! - **CPU halt**: The `wfi` (Wait For Interrupt) instruction suspends
//!   execution until an interrupt arrives.
//! - **AP boot**: PSCI `CPU_ON` (function ID 0x84000003) is invoked via
//!   `hvc #0` to power on a secondary CPU at a given entry point.
//!
//! # Anti-translate vs C
//!
//! Minix3's C SMP layer (arch/i386/smp.c) dispatches architecture operations
//! through global function pointers (`arch_send_smp_schedule_ipi`,
//! `arch_smp_halt_cpu`, `ipi_ack`) that are patched in during `arch_init`.
//! This Rust backend anti-translates that design: instead of indirect calls
//! through global state, each operation talks directly to the hardware via
//! system-register accesses (`mrs`/`msr` for the GIC CPU interface) and a
//! single MMIO write (GICD_SGIR). The only piece of boot-time data retained
//! is the GIC distributor base address — a value, not a function pointer —
//! stored in a per-arch static (see `16-smp.md` §3 D7). This keeps the IPI
//! hot path a direct MMIO store / system-register sequence with no indirect
//! call.
//!
//! C: arch/earm/smp.c — ARM EABI equivalent of arch/i386/smp.c (the
//!    aarch64-specific smp.c may not exist in Minix3; this is the
//!    architecture equivalent of arch/i386/smp.c).

use crate::smp::SmpArch;

/// GICD_SGIR register offset from the GIC distributor base address.
///
/// Writing this register generates a Software Generated Interrupt (SGI).
/// ARM GIC Architecture Specification §4.3.22 (GICD_SGIR).
const GICD_SGIR: usize = 0xF00;

/// GICD_SGIR target list filter: send to the CPU(s) specified in the CPU
/// target list field (bits [23:16]). Value 0b00 in bits [25:24]. ARM GIC
/// Architecture Specification §4.3.22.
const SGIR_TARGET_LIST_FILTER: u32 = 0 << 24;

/// SGI INTID used for the schedule IPI. SGIs occupy INTID range 0..15;
/// we use ID 0. ARM GIC Architecture Specification §4.3.22.
const SCHED_SGI_INTID: u32 = 0;

/// PSCI `CPU_ON` function ID, SMC32/HVC32 calling convention (bit 31 set,
/// 32-bit). The SMC64 equivalent is 0xC4000003. ARM DEN 0022D (PSCI) §5.4.3.
const PSCI_CPU_ON_32: u64 = 0x8400_0003;

/// GIC distributor base address, populated during `arch_init`.
///
/// This is the only mutable global in the ARM64 SMP backend: the physical
/// base of the GIC distributor MMIO region. Unlike the C port's function
/// pointers, this holds a *value* (a base address); all behavior is encoded
/// inline in the trait methods, so the IPI hot path remains a direct MMIO
/// write with no indirect call. See `16-smp.md` §3 D7.
///
/// # Safety invariant
///
/// Must be set to the distributor base (a valid MMIO physical address) via
/// `set_gicd_base` before any `send_sched_ipi` call. Until then it is 0 and
/// IPI sends must not be attempted.
static mut GICD_BASE: usize = 0;

/// Record the GIC distributor base address.
///
/// Called from `arch_init` once firmware (TF-A/U-Boot) has provided the GIC
/// descriptor. After this call, `send_sched_ipi` is safe to use.
///
/// Currently wired up by `arch_init` on real hardware; `#[allow(dead_code)]`
/// keeps the linker quiet for host/mock builds that never call it.
///
/// # Safety
///
/// Writes to a `static mut`. The caller must ensure no other CPU is
/// concurrently reading `GICD_BASE` (typically called single-threaded
/// during early boot before APs are released).
#[inline]
#[allow(dead_code)]
pub(crate) unsafe fn set_gicd_base(base: usize) {
    GICD_BASE = base;
}

/// Read the GIC distributor base address.
///
/// # Safety
///
/// Reads a `static mut`. Safe in practice once `arch_init` has populated
/// it; the read itself is non-tearing on aarch64.
#[inline]
unsafe fn gicd_base() -> usize {
    GICD_BASE
}

/// ARM64 SMP backend using the GICv3 interrupt controller.
///
/// This is a zero-sized type — the only hardware parameter (the GIC
/// distributor base) lives in the `GICD_BASE` static, and all CPU-interface
/// state is reached through system registers.
///
/// C: arch/earm/smp.c (architecture equivalent of arch/i386/smp.c)
pub struct AArch64SmpArch;

impl SmpArch for AArch64SmpArch {
    #[inline]
    fn send_sched_ipi(cpu: u32) {
        // C: arch_send_smp_schedule_ipi(cpu) — smp.c:65
        //
        // Generate SGI 0 targeting a single CPU by writing GICD_SGIR.
        // GICD_SGIR layout (ARM GIC Architecture Specification §4.3.22):
        //   Bits [25:24]: Target List Filter — 0 = send to the CPU(s)
        //                 specified in the CPU target list.
        //   Bits [23:16]: CPU Target List — one bit per CPU in the
        //                 affinity 0 cluster (bit n = CPU n). The field is
        //                 8 bits wide, so this targets CPUs 0..7 (single-
        //                 cluster simplification; GICv3 ARE mode would use
        //                 ICC_SGI0R_EL1 for full affinity routing).
        //   Bits [3:0]:   SGI INTID (0..15). We use 0 for schedule IPI.
        //
        // The CPU id is masked to 3 bits to stay within the 8-bit target
        // list and to keep the shift in range (no undefined shift).
        let target_list = 1u32 << (cpu & 0x07);
        let sgir = SGIR_TARGET_LIST_FILTER | (target_list << 16) | (SCHED_SGI_INTID & 0x0F);

        // SAFETY: `gicd_base()` reads the distributor base set by
        // `arch_init` via `set_gicd_base`. Writing GICD_SGIR is a
        // side-effecting MMIO store that raises an SGI on the target CPU;
        // `write_volatile` prevents the compiler from eliding it. The
        // address is a valid MMIO region once `set_gicd_base` has run.
        unsafe {
            let addr = (gicd_base() + GICD_SGIR) as *mut u32;
            core::ptr::write_volatile(addr, sgir);
        }
    }

    #[inline]
    fn halt_cpu() {
        // C: arch_smp_halt_cpu() — smp.c:60
        //
        // `wfi` (Wait For Interrupt) suspends execution until an interrupt
        // (or debug event) arrives. ARM ARM §C6.2.
        //
        // SAFETY: `wfi` is a hint instruction; it never faults. Safe in
        // kernel mode with interrupts enabled (otherwise it may spin
        // indefinitely). `nomem`/`nostack` mirror the x86_64 `hlt` usage.
        unsafe {
            core::arch::asm!("wfi", options(nomem, nostack));
        }
    }

    fn idle_halt() {
        // C: halt_cpu() — klib.S:407-414 (idle-loop variant: `sti; hlt`).
        //
        // aarch64 equivalent: unmask IRQs (`daifclr, #2` clears the I mask
        // — DAIF I-bit, ARM ARM §D1.12) then `wfi`. As on x86_64, the mask
        // must be cleared before waiting or the CPU never wakes. `wfi`
        // returns when any pending interrupt is taken (the IRQ entry then
        // runs with interrupts masked by hardware PSTATE masking).
        //
        // SAFETY: `msr daifclr` and `wfi` are privileged but confined:
        // the first only unmasks IRQs, the second only sleeps the CPU.
        // Safe in EL1 kernel mode.
        unsafe {
            core::arch::asm!(
                "msr daifclr, #2",
                "wfi",
                options(nomem, nostack)
            );
        }
    }

    #[inline]
    fn ack_ipi() {
        // C: ipi_ack() — smp.c:58,198
        //
        // GICv3 interrupt acknowledgement is a two-step system-register
        // dance (ARM GIC Architecture Specification §4.3.7, §4.3.8):
        //   1. Read ICC_IAR1_EL1 — atomically drops the priority of the
        //      current interrupt and returns its INTID.
        //   2. Write that INTID to ICC_EOIR1_EL1 — signals end of
        //      interrupt, allowing re-entrancy of the same INTID.
        //
        // The `SmpArch::ack_ipi` contract has no return value, so the
        // INTID read here is consumed locally and written straight back to
        // ICC_EOIR1_EL1. This is the simplified acknowledgement used on the
        // IPI path: the actual dispatch already happened in the trap
        // handler before this is called.
        let intid: u64;
        // SAFETY: Both instructions are emitted in one asm block so the
        // IAR read is guaranteed to precede the EOIR write. `mrs` reads
        // ICC_IAR1_EL1 (priority drop + INTID return) and `msr` writes the
        // same INTID to ICC_EOIR1_EL1. These are the standard
        // interrupt-acknowledge system-register accesses at EL1; they do
        // not touch Rust memory, and `nostack` holds because no stack
        // access is involved.
        unsafe {
            core::arch::asm!(
                "mrs {intid}, icc_iar1_el1",
                "msr icc_eoir1_el1, {intid}",
                intid = out(reg) intid,
                options(nostack),
            );
        }
        // Intentionally unused: the INTID is consumed by the EOIR write
        // above; nothing else needs it under the simplified ack contract.
        let _ = intid;
    }

    #[inline]
    fn boot_ap(cpu: u32, entry: usize) {
        // C: AP boot protocol — arch/i386/smp.c (architecture equivalent)
        //
        // ARM64 secondary CPUs are powered on by firmware through PSCI
        // (Power State Coordination Interface, ARM DEN 0022D). We issue the
        // `CPU_ON` call via `hvc #0` (hypervisor conduit). The SMC64
        // variant (0xC4000003) would be used with `smc #0` if the conduit
        // were the secure monitor.
        //
        // PSCI CPU_ON parameters (SMC32/HVC32 calling convention):
        //   x0 = function ID  (0x84000003)
        //   x1 = target_cpu   (MPIDR-based affinity of the secondary CPU)
        //   x2 = entry_point  (physical address of AP trampoline)
        //   x3 = context_id   (opaque cookie passed to the AP; 0 here)
        // On success x0 = 0 (PSCI_SUCCESS); a non-zero value is an error.
        //
        // We use the linear CPU id as the MPIDR target. Real MPIDR encoding
        // uses affinity fields (Aff0..Aff3); a production port would
        // translate cpu -> MPIDR via a per-platform table. This
        // simplification matches the single-cluster boot model.
        let fid = PSCI_CPU_ON_32;
        let target_cpu = cpu as u64;
        let entry_point = entry as u64;
        let context_id: u64 = 0;
        let ret: u64;

        // SAFETY: `hvc #0` traps to the hypervisor/firmware PSCI handler.
        // All argument registers (x0..x3) are explicitly initialized. The
        // call is side-effecting (powers on another CPU) and may
        // synchronize with the incoming AP, so `nomem` is deliberately not
        // set; `nostack` is set because hvc does not access the stack. x0
        // carries the PSCI return code.
        unsafe {
            core::arch::asm!(
                "hvc #0",
                inout("x0") fid => ret,
                in("x1") target_cpu,
                in("x2") entry_point,
                in("x3") context_id,
                options(nostack),
            );
        }
        // Non-zero return indicates a PSCI error (e.g. already_on,
        // invalid_params). We do not propagate it: the trait contract is
        // best-effort fire-and-forget, mirroring the C port.
        let _ = ret;
    }

    fn current_cpu() -> u32 {
        // C: `cpuid` reads from per-CPU kernel stack top.
        // Rust: read MPIDR_EL1 and extract Aff0 (low 8 bits).
        //
        // MPIDR_EL1: bits 0-7 hold Aff0 (CPU ID within a cluster).
        // ARM ARM D7.2.94. In a single-cluster system, Aff0 == logical
        // CPU ID (0, 1, 2, ...).
        //
        // SAFETY: `mrs` reads a system register. MPIDR_EL1 is accessible
        // at all exception levels and has no side effects.
        let mpidr: u64;
        unsafe {
            core::arch::asm!(
                "mrs {0}, mpidr_el1",
                out(reg) mpidr,
                options(nomem, nostack),
            );
        }
        (mpidr & 0xFF) as u32
    }
}
