[package]
name = "minix-fs-rt"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "minix_fs_rt"
path = "src/lib.rs"

[dependencies]
minix-types = { workspace = true }
minix-sys = { workspace = true }
minix-sef = { workspace = true }
minix-fs = { workspace = true }
