[package]
name = "minix-driver-vt6105"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "minix-driver-vt6105"
path = "src/main.rs"

[dependencies]
minix-types = { workspace = true }
minix-sys = { workspace = true }

[lib]
name = "minix_driver_vt6105"
path = "src/lib.rs"
