[package]
name = "minix-driver-ahci"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "minix-driver-ahci"
path = "src/main.rs"

[dependencies]
minix-blockdriver = { workspace = true }
minix-chardriver = { workspace = true }
minix-driver-rt = { workspace = true }
minix-types = { workspace = true }
minix-sys = { workspace = true }

[lib]
name = "minix_driver_ahci"
path = "src/lib.rs"
