[package]
name = "minix-fs-vbfs"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "minix-fs-vbfs"
path = "src/main.rs"

[dependencies]
minix-types = { workspace = true }
minix-sys = { workspace = true }

[lib]
name = "minix_fs_vbfs"
path = "src/lib.rs"
