[package]
name = "minix-kernel"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "minix_kernel"
path = "src/lib.rs"

[[bin]]
name = "minix-kernel"
path = "src/main.rs"
test = false
doctest = false
bench = false

[dependencies]
minix-ipc = { workspace = true }
minix-types = { workspace = true }
minix-mock = { workspace = true, optional = true }

[features]
default = ["mock"]
mock = ["dep:minix-mock"]

[profile.dev]
opt-level = 0
debug = true
panic = "abort"

[profile.release]
opt-level = 3
lto = true
panic = "abort"
