[package]
name = "minix-kernel"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "minix_kernel"
path = "src/lib.rs"

[dependencies]
minix-arch = { path = "../arch", default-features = false }
minix-ipc = { workspace = true }
minix-types = { workspace = true }
minix-boot = { workspace = true }
minix-mock = { workspace = true, optional = true }
bitflags = { workspace = true }

[dev-dependencies]
minix-arch = { path = "../arch", features = ["mock"] }

[features]
default = ["mock"]
mock = ["dep:minix-mock"]
qemu_test = []

[profile.dev]
opt-level = 0
debug = true
panic = "abort"

[profile.release]
opt-level = 3
lto = true
panic = "abort"
